version: '3.8'

services:
  memora-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1212:1212"
    restart: unless-stopped
    environment:
      - PORT=1212
    healthcheck:
      test: ["CMD-SHELL", "pgrep memora-server || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s